const Constants = {

	TILE_SIZE: 64,
	HALF_TILE_SIZE: 32,
	CELL_WIDTH: 3,
	CELL_HEIGHT: 1,
	GRID_WIDTH: 3,
	GRID_HEIGHT: 3,

	PLAYER_START_X: 480,
	PLAYER_START_Y: -512,
	PLAYER_JUMP_SPEED: -25,
	CAMERA_START_X: -320,
};