const Constants = {

	TILE_SIZE: 64,
	HALF_TILE_SIZE: 32,
	CELL_WIDTH: 3,
	CELL_HEIGHT: 1,
	GRID_WIDTH: 3,
	GRID_HEIGHT: 3,

	LERP_SPEED: 0.1, // bigger is faster
	LERP_THRESHOLD: 10, // stop lerping
	PARALAX_SPEED: 0.02,

	GRAVITY: 2,

	PLAYER_START_X: 480,
	PLAYER_START_Y: -256,
	PLAYER_SPEED: 3,
	PLAYER_JUMP_SPEED: -16,
	CAMERA_START_X: -320,

	SPEED_CHANGE: 0.125,

	PLAYER_CATEGORY: 0x0002,
	PLATFORM_CATEGORY: 0x0004,
	TRIGGER_CATEGORY: 0x0008,

	LEVEL_RINGS: 5,
	REMOVE_RINGS: 8,

};